- name: "Copy health_alarm_notify.conf"
  template:
    src: "health_alarm_notify.conf.j2"
    dest: "/etc/netdata/health_alarm_notify.conf"
    mode: 0644
  notify: ['Restart Netdata service']
  
- name: "Get API Key"
  slurp:
    src: /var/lib/netdata/netdata.api.key
  register: apikey
  tags:
  - silence
  
- name: "Reset all alarms"
  uri:
    url: "{{ netdata_url }}:{{ netdata_config['web']['bind to']split(':')[1] }}/api/v1/manage/health?cmd=RESET"
    headers:
      X-Auth-Token: "{{ apikey.content | b64decode }}"
    validate_certs: "{{ netdata_validate_certs | default('yes') }}"
  become: no
  tags:
  - silence

- name: "Silence alarms"
  uri:
    url: "{{ netdata_url }}:{{ netdata_config['web']['bind to']split(':')[1] }}/api/v1/manage/health?cmd=SILENCE&{{ item }}"
    headers:
      X-Auth-Token: "{{ apikey.content | b64decode }}"
    validate_certs: "{{ netdata_validate_certs | default('yes') }}"
  become: no
  with_items: "{{ netdata_silenced_alarms | default ([]) }}"
  tags:
  - silence
