---
# Netdata Tasks
- name: "Check if netdata available"
  shell:
    cmd: netdata -versio
  register: result
  ignore_errors: True
  changed_when: result.rc != 0

- include_tasks: install.yml
  when: result.rc != 0 or (netdata_force_install is defined and netdata_force_install)
  
- include_tasks: configure.yml

- include_tasks: plugins.yml

- include_tasks: mods.yml

- name: "Debug"
  ansible.builtin.debug:
    var: netdata_skip_claim
    
- include_tasks: claim.yml
  when: netdata_force_install is not defined or not netdata_skip_claim
  
- include_tasks: alarms.yml

- include_tasks: clean.yml
