---
# Netdata Tasks
- include_tasks: install.yml

- include_tasks: configure.yml

- include_tasks: plugins.yml

- include_tasks: mods.yml

- include_tasks: claim.yml

- include_tasks: alarms.yml

- include_tasks: clean.yml
